apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 4 
  selector:
    matchLabels:
      env: demo
